server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9999/realms/hotel"
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
